<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.21.0" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.21.0" />
    <PackageReference Include="MiniProfiler.AspNetCore.Mvc" Version="4.5.4" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.Filters" Version="10.0.1" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.21.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BearPlan.Core\BearPlan.Core.csproj" />
    <ProjectReference Include="..\BearPlan.Common\BearPlan.Common.csproj" />
    <ProjectReference Include="..\BearPlan.Business\BearPlan.Business.csproj" />
    <ProjectReference Include="..\BearPlan.EventBus\BearPlan.EventBus.csproj" />
    <ProjectReference Include="..\BearPlan.TaskService\BearPlan.TaskService.csproj" />
    <ProjectReference Include="..\BearPlan.Repository\BearPlan.Repository.csproj" />
  </ItemGroup>

</Project>
