//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BearPlan.Common.MultiLanguage.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BearPlan.Common.MultiLanguage.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刷新Api失败.
        /// </summary>
        public static string Action_ApiRefresh_Fail {
            get {
                return ResourceManager.GetString("Action_ApiRefresh_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刷新Api成功.
        /// </summary>
        public static string Action_ApiRefresh_Success {
            get {
                return ResourceManager.GetString("Action_ApiRefresh_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 构建登录菜单.
        /// </summary>
        public static string Action_BuildLoginMenu {
            get {
                return ResourceManager.GetString("Action_BuildLoginMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 执行作业.
        /// </summary>
        public static string Action_ExecuteJob {
            get {
                return ResourceManager.GetString("Action_ExecuteJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 执行作业日志.
        /// </summary>
        public static string Action_ExecutionLogJob {
            get {
                return ResourceManager.GetString("Action_ExecutionLogJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取全部Api.
        /// </summary>
        public static string Action_GetAllApi {
            get {
                return ResourceManager.GetString("Action_GetAllApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取全部岗位.
        /// </summary>
        public static string Action_GetAllJobs {
            get {
                return ResourceManager.GetString("Action_GetAllJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取全部菜单.
        /// </summary>
        public static string Action_GetAllMenu {
            get {
                return ResourceManager.GetString("Action_GetAllMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取全部角色.
        /// </summary>
        public static string Action_GetAllRole {
            get {
                return ResourceManager.GetString("Action_GetAllRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取全部子菜单.
        /// </summary>
        public static string Action_GetAllSubMenu {
            get {
                return ResourceManager.GetString("Action_GetAllSubMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取全部租户.
        /// </summary>
        public static string Action_GetAllTenant {
            get {
                return ResourceManager.GetString("Action_GetAllTenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取Api分组.
        /// </summary>
        public static string Action_GetApiGroup {
            get {
                return ResourceManager.GetString("Action_GetApiGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取部门树形数据.
        /// </summary>
        public static string Action_GetDeptTreeData {
            get {
                return ResourceManager.GetString("Action_GetDeptTreeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取邮箱验证码.
        /// </summary>
        public static string Action_GetEmailVerificationCode {
            get {
                return ResourceManager.GetString("Action_GetEmailVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取角色等级.
        /// </summary>
        public static string Action_GetRoleLevel {
            get {
                return ResourceManager.GetString("Action_GetRoleLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取同级父级部门数据.
        /// </summary>
        public static string Action_GetSiblingAndParentDepts {
            get {
                return ResourceManager.GetString("Action_GetSiblingAndParentDepts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取同级父级菜单数据.
        /// </summary>
        public static string Action_GetSiblingAndParentMenus {
            get {
                return ResourceManager.GetString("Action_GetSiblingAndParentMenus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取子菜单.
        /// </summary>
        public static string Action_GetSubMenu {
            get {
                return ResourceManager.GetString("Action_GetSubMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取验证码.
        /// </summary>
        public static string Action_GetVerificationCode {
            get {
                return ResourceManager.GetString("Action_GetVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暂停作业.
        /// </summary>
        public static string Action_PauseJob {
            get {
                return ResourceManager.GetString("Action_PauseJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 个人信息.
        /// </summary>
        public static string Action_PersonalInfo {
            get {
                return ResourceManager.GetString("Action_PersonalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刷新Api.
        /// </summary>
        public static string Action_RefreshApi {
            get {
                return ResourceManager.GetString("Action_RefreshApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刷新Token.
        /// </summary>
        public static string Action_RefreshToken {
            get {
                return ResourceManager.GetString("Action_RefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 恢复作业.
        /// </summary>
        public static string Action_ResumeJob {
            get {
                return ResourceManager.GetString("Action_ResumeJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 服务器资源信息.
        /// </summary>
        public static string Action_ServerResourceInfo {
            get {
                return ResourceManager.GetString("Action_ServerResourceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动失败.
        /// </summary>
        public static string Action_StartupFailure {
            get {
                return ResourceManager.GetString("Action_StartupFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动成功.
        /// </summary>
        public static string Action_StartupSuccess {
            get {
                return ResourceManager.GetString("Action_StartupSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新头像.
        /// </summary>
        public static string Action_UpdateAvatar {
            get {
                return ResourceManager.GetString("Action_UpdateAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新邮箱.
        /// </summary>
        public static string Action_UpdateEmail {
            get {
                return ResourceManager.GetString("Action_UpdateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新密码.
        /// </summary>
        public static string Action_UpdatePassword {
            get {
                return ResourceManager.GetString("Action_UpdatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新个人信息.
        /// </summary>
        public static string Action_UpdatePersonalInfo {
            get {
                return ResourceManager.GetString("Action_UpdatePersonalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新角色Api.
        /// </summary>
        public static string Action_UpdateRoleApi {
            get {
                return ResourceManager.GetString("Action_UpdateRoleApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新角色菜单.
        /// </summary>
        public static string Action_UpdateRoleMenu {
            get {
                return ResourceManager.GetString("Action_UpdateRoleMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户行为.
        /// </summary>
        public static string Action_UserConduct {
            get {
                return ResourceManager.GetString("Action_UserConduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户登录.
        /// </summary>
        public static string Action_UserLogin {
            get {
                return ResourceManager.GetString("Action_UserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户登出.
        /// </summary>
        public static string Action_UserLogOut {
            get {
                return ResourceManager.GetString("Action_UserLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看单一角色信息.
        /// </summary>
        public static string Action_ViewSingleRole {
            get {
                return ResourceManager.GetString("Action_ViewSingleRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api分组.
        /// </summary>
        public static string Api_Group {
            get {
                return ResourceManager.GetString("Api_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api请求方法.
        /// </summary>
        public static string Api_Method {
            get {
                return ResourceManager.GetString("Api_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api Url.
        /// </summary>
        public static string Api_Url {
            get {
                return ResourceManager.GetString("Api_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 应用ID.
        /// </summary>
        public static string App_AppId {
            get {
                return ResourceManager.GetString("App_AppId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 应用名称.
        /// </summary>
        public static string App_AppName {
            get {
                return ResourceManager.GetString("App_AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 应用密钥.
        /// </summary>
        public static string App_AppSecretKey {
            get {
                return ResourceManager.GetString("App_AppSecretKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 备注.
        /// </summary>
        public static string App_Remark {
            get {
                return ResourceManager.GetString("App_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api管理.
        /// </summary>
        public static string Area_ApiManagement {
            get {
                return ResourceManager.GetString("Area_ApiManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 应用密钥管理.
        /// </summary>
        public static string Area_ApplicationKeyManagement {
            get {
                return ResourceManager.GetString("Area_ApplicationKeyManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作日志管理.
        /// </summary>
        public static string Area_AuditLogManagement {
            get {
                return ResourceManager.GetString("Area_AuditLogManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 授权管理.
        /// </summary>
        public static string Area_AuthorizationManagement {
            get {
                return ResourceManager.GetString("Area_AuthorizationManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部门管理.
        /// </summary>
        public static string Area_DeptManagement {
            get {
                return ResourceManager.GetString("Area_DeptManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字典详情管理.
        /// </summary>
        public static string Area_DictionaryDetailManagement {
            get {
                return ResourceManager.GetString("Area_DictionaryDetailManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字典管理.
        /// </summary>
        public static string Area_DictionaryManagement {
            get {
                return ResourceManager.GetString("Area_DictionaryManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 邮箱账户管理.
        /// </summary>
        public static string Area_EmailAccountManagement {
            get {
                return ResourceManager.GetString("Area_EmailAccountManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 邮件模板管理.
        /// </summary>
        public static string Area_EmailMessageTemplateManagement {
            get {
                return ResourceManager.GetString("Area_EmailMessageTemplateManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 异常日志管理.
        /// </summary>
        public static string Area_ExceptionLogManagement {
            get {
                return ResourceManager.GetString("Area_ExceptionLogManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件存储管理.
        /// </summary>
        public static string Area_FileStorageManagement {
            get {
                return ResourceManager.GetString("Area_FileStorageManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统配置.
        /// </summary>
        public static string Area_GlobalSettingManagement {
            get {
                return ResourceManager.GetString("Area_GlobalSettingManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 岗位管理.
        /// </summary>
        public static string Area_JobManagement {
            get {
                return ResourceManager.GetString("Area_JobManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作业管理.
        /// </summary>
        public static string Area_JobSchedulingManagement {
            get {
                return ResourceManager.GetString("Area_JobSchedulingManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 邮件队列管理.
        /// </summary>
        public static string Area_MailQueueManagement {
            get {
                return ResourceManager.GetString("Area_MailQueueManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 菜单管理.
        /// </summary>
        public static string Area_MenuManagement {
            get {
                return ResourceManager.GetString("Area_MenuManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 角色授权管理.
        /// </summary>
        public static string Area_RoleAuthorizationManagement {
            get {
                return ResourceManager.GetString("Area_RoleAuthorizationManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 角色管理.
        /// </summary>
        public static string Area_RoleManagement {
            get {
                return ResourceManager.GetString("Area_RoleManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 服务器资源管理.
        /// </summary>
        public static string Area_ServerResourceManagement {
            get {
                return ResourceManager.GetString("Area_ServerResourceManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作业日志管理.
        /// </summary>
        public static string Area_TaskLogManagement {
            get {
                return ResourceManager.GetString("Area_TaskLogManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 租户管理.
        /// </summary>
        public static string Area_TenantManagement {
            get {
                return ResourceManager.GetString("Area_TenantManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户管理.
        /// </summary>
        public static string Area_UserManagement {
            get {
                return ResourceManager.GetString("Area_UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}=&gt;{1}=&gt;已存在!.
        /// </summary>
        public static string Arg0_Arg1_IsExist {
            get {
                return ResourceManager.GetString("Arg0_Arg1_IsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}=&gt;{1}=&gt;不存在!.
        /// </summary>
        public static string Arg0_Arg1_NotExist {
            get {
                return ResourceManager.GetString("Arg0_Arg1_NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 集合必须至少包含一个项目.
        /// </summary>
        public static string Arg0_AtLeastOne {
            get {
                return ResourceManager.GetString("Arg0_AtLeastOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 格式错误.
        /// </summary>
        public static string Arg0_Error_Format {
            get {
                return ResourceManager.GetString("Arg0_Error_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 未激活.
        /// </summary>
        public static string Arg0_NotActivated {
            get {
                return ResourceManager.GetString("Arg0_NotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 必须是数字.
        /// </summary>
        public static string Arg0_number {
            get {
                return ResourceManager.GetString("Arg0_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}至少是{1}.
        /// </summary>
        public static string Arg0_range_Arg1 {
            get {
                return ResourceManager.GetString("Arg0_range_Arg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}必须是{1}到{2}之间的数.
        /// </summary>
        public static string Arg0_range_Arg1_Arg2 {
            get {
                return ResourceManager.GetString("Arg0_range_Arg1_Arg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}最多是{1}.
        /// </summary>
        public static string Arg0_range_Arg2 {
            get {
                return ResourceManager.GetString("Arg0_range_Arg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 是必填项.
        /// </summary>
        public static string Arg0_required {
            get {
                return ResourceManager.GetString("Arg0_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}最多输入{1}个字符.
        /// </summary>
        public static string Arg0_stringmax_Arg1 {
            get {
                return ResourceManager.GetString("Arg0_stringmax_Arg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否启用.
        /// </summary>
        public static string Dept_Enabled {
            get {
                return ResourceManager.GetString("Dept_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部门名称.
        /// </summary>
        public static string Dept_Name {
            get {
                return ResourceManager.GetString("Dept_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部门父ID.
        /// </summary>
        public static string Dept_PId {
            get {
                return ResourceManager.GetString("Dept_PId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 子部门个数.
        /// </summary>
        public static string Dept_SubCount {
            get {
                return ResourceManager.GetString("Dept_SubCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字典ID.
        /// </summary>
        public static string Dict_Detail_DictId {
            get {
                return ResourceManager.GetString("Dict_Detail_DictId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字典标签.
        /// </summary>
        public static string Dict_Detail_Label {
            get {
                return ResourceManager.GetString("Dict_Detail_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字典值.
        /// </summary>
        public static string Dict_Detail_Value {
            get {
                return ResourceManager.GetString("Dict_Detail_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字典名称.
        /// </summary>
        public static string Dict_Name {
            get {
                return ResourceManager.GetString("Dict_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字典类型.
        /// </summary>
        public static string Dict_Type {
            get {
                return ResourceManager.GetString("Dict_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示名称.
        /// </summary>
        public static string EmailAccount_DisplayName {
            get {
                return ResourceManager.GetString("EmailAccount_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 电子邮件.
        /// </summary>
        public static string EmailAccount_Email {
            get {
                return ResourceManager.GetString("EmailAccount_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否SSL.
        /// </summary>
        public static string EmailAccount_EnableSsl {
            get {
                return ResourceManager.GetString("EmailAccount_EnableSsl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主机.
        /// </summary>
        public static string EmailAccount_Host {
            get {
                return ResourceManager.GetString("EmailAccount_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码.
        /// </summary>
        public static string EmailAccount_Password {
            get {
                return ResourceManager.GetString("EmailAccount_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 端口.
        /// </summary>
        public static string EmailAccount_Port {
            get {
                return ResourceManager.GetString("EmailAccount_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用默认系统凭据.
        /// </summary>
        public static string EmailAccount_UseDefaultCredentials {
            get {
                return ResourceManager.GetString("EmailAccount_UseDefaultCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账户名称.
        /// </summary>
        public static string EmailAccount_Username {
            get {
                return ResourceManager.GetString("EmailAccount_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抄送邮箱地址.
        /// </summary>
        public static string EmailTemplate_BccEmailAddresses {
            get {
                return ResourceManager.GetString("EmailTemplate_BccEmailAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发送内容.
        /// </summary>
        public static string EmailTemplate_Body {
            get {
                return ResourceManager.GetString("EmailTemplate_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发送邮箱账户.
        /// </summary>
        public static string EmailTemplate_EmailAccountId {
            get {
                return ResourceManager.GetString("EmailTemplate_EmailAccountId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否激活.
        /// </summary>
        public static string EmailTemplate_IsActive {
            get {
                return ResourceManager.GetString("EmailTemplate_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模板名称.
        /// </summary>
        public static string EmailTemplate_Name {
            get {
                return ResourceManager.GetString("EmailTemplate_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发送主题.
        /// </summary>
        public static string EmailTemplate_Subject {
            get {
                return ResourceManager.GetString("EmailTemplate_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全部.
        /// </summary>
        public static string Enum_DataScope_All {
            get {
                return ResourceManager.GetString("Enum_DataScope_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自定义.
        /// </summary>
        public static string Enum_DataScope_Customize {
            get {
                return ResourceManager.GetString("Enum_DataScope_Customize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本部门.
        /// </summary>
        public static string Enum_DataScope_MyDept {
            get {
                return ResourceManager.GetString("Enum_DataScope_MyDept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本部门及以下.
        /// </summary>
        public static string Enum_DataScope_MyDeptAndBelow {
            get {
                return ResourceManager.GetString("Enum_DataScope_MyDeptAndBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本人.
        /// </summary>
        public static string Enum_DataScope_MySelf {
            get {
                return ResourceManager.GetString("Enum_DataScope_MySelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MySql.
        /// </summary>
        public static string Enum_Db_MySql {
            get {
                return ResourceManager.GetString("Enum_Db_MySql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oracle.
        /// </summary>
        public static string Enum_Db_Oracle {
            get {
                return ResourceManager.GetString("Enum_Db_Oracle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostgreSQL.
        /// </summary>
        public static string Enum_Db_PostgreSQL {
            get {
                return ResourceManager.GetString("Enum_Db_PostgreSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sqlite.
        /// </summary>
        public static string Enum_Db_Sqlite {
            get {
                return ResourceManager.GetString("Enum_Db_Sqlite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SqlServer.
        /// </summary>
        public static string Enum_Db_SqlServer {
            get {
                return ResourceManager.GetString("Enum_Db_SqlServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 业务类.
        /// </summary>
        public static string Enum_Dict_Business {
            get {
                return ResourceManager.GetString("Enum_Dict_Business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统类.
        /// </summary>
        public static string Enum_Dict_System {
            get {
                return ResourceManager.GetString("Enum_Dict_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 否.
        /// </summary>
        public static string Enum_False {
            get {
                return ResourceManager.GetString("Enum_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 按钮.
        /// </summary>
        public static string Enum_Menu_Button {
            get {
                return ResourceManager.GetString("Enum_Menu_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目录.
        /// </summary>
        public static string Enum_Menu_Catalog {
            get {
                return ResourceManager.GetString("Enum_Menu_Catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 菜单.
        /// </summary>
        public static string Enum_Menu_Menu {
            get {
                return ResourceManager.GetString("Enum_Menu_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Db隔离.
        /// </summary>
        public static string Enum_Tenant_Db {
            get {
                return ResourceManager.GetString("Enum_Tenant_Db", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id隔离.
        /// </summary>
        public static string Enum_Tenant_Id {
            get {
                return ResourceManager.GetString("Enum_Tenant_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 阻塞.
        /// </summary>
        public static string Enum_Trigger_Blocked {
            get {
                return ResourceManager.GetString("Enum_Trigger_Blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完成.
        /// </summary>
        public static string Enum_Trigger_Complete {
            get {
                return ResourceManager.GetString("Enum_Trigger_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cron模式.
        /// </summary>
        public static string Enum_Trigger_Cron {
            get {
                return ResourceManager.GetString("Enum_Trigger_Cron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误.
        /// </summary>
        public static string Enum_Trigger_Error {
            get {
                return ResourceManager.GetString("Enum_Trigger_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 阻塞.
        /// </summary>
        public static string Enum_Trigger_None {
            get {
                return ResourceManager.GetString("Enum_Trigger_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 运行中.
        /// </summary>
        public static string Enum_Trigger_Normal {
            get {
                return ResourceManager.GetString("Enum_Trigger_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未运行.
        /// </summary>
        public static string Enum_Trigger_NotRunning {
            get {
                return ResourceManager.GetString("Enum_Trigger_NotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暂停.
        /// </summary>
        public static string Enum_Trigger_Paused {
            get {
                return ResourceManager.GetString("Enum_Trigger_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple模式.
        /// </summary>
        public static string Enum_Trigger_Simple {
            get {
                return ResourceManager.GetString("Enum_Trigger_Simple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是.
        /// </summary>
        public static string Enum_True {
            get {
                return ResourceManager.GetString("Enum_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账户已锁定，请稍后重试。解锁时间：{0}.
        /// </summary>
        public static string Error_AccountLockedWithUnlockTime_Arg0 {
            get {
                return ResourceManager.GetString("Error_AccountLockedWithUnlockTime_Arg0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已在运行，请勿重复开启！.
        /// </summary>
        public static string Error_AlreadyRunning {
            get {
                return ResourceManager.GetString("Error_AlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppSetting.json 的 DataConnection 配置错误，请检查！.
        /// </summary>
        public static string Error_AppSettings_DataConnection {
            get {
                return ResourceManager.GetString("Error_AppSettings_DataConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 条件表达式和条件模型不能同时使用.
        /// </summary>
        public static string Error_ConditionConflict {
            get {
                return ResourceManager.GetString("Error_ConditionConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请确认配置库 ID:{0} 的 Enabled 为 true.
        /// </summary>
        public static string Error_ConfigProviderDatabase_EnsureEnabled_Arg0 {
            get {
                return ResourceManager.GetString("Error_ConfigProviderDatabase_EnsureEnabled_Arg0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 存在数据关联，请解除后再试！.
        /// </summary>
        public static string Error_DataAssociationExists {
            get {
                return ResourceManager.GetString("Error_DataAssociationExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请确认主库 ID:{0} 的 Enabled 为 true.
        /// </summary>
        public static string Error_Database_EnsureEnabled_Arg0 {
            get {
                return ResourceManager.GetString("Error_Database_EnsureEnabled_Arg0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请确认数据库 ID:{0} 对应的从库的 Enabled 为 true.
        /// </summary>
        public static string Error_Database_SlaveEnsureEnabled_Arg0 {
            get {
                return ResourceManager.GetString("Error_Database_SlaveEnsureEnabled_Arg0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据不存在.
        /// </summary>
        public static string Error_DataNotExist {
            get {
                return ResourceManager.GetString("Error_DataNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 禁止重复调用.
        /// </summary>
        public static string Error_DuplicateCallNotAllowed {
            get {
                return ResourceManager.GetString("Error_DuplicateCallNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 执行失败，请重试！.
        /// </summary>
        public static string Error_ExecutionFailed {
            get {
                return ResourceManager.GetString("Error_ExecutionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件过大，请选择文件小于等于{0}MB的重新进行尝试!.
        /// </summary>
        public static string Error_FileTooLarge_Arg0 {
            get {
                return ResourceManager.GetString("Error_FileTooLarge_Arg0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 禁止删除自己.
        /// </summary>
        public static string Error_ForbidToDeleteYourself {
            get {
                return ResourceManager.GetString("Error_ForbidToDeleteYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 旧密码错误.
        /// </summary>
        public static string Error_IncorrectOldPassword {
            get {
                return ResourceManager.GetString("Error_IncorrectOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 两次输入不匹配.
        /// </summary>
        public static string Error_InputsDoNotMatch {
            get {
                return ResourceManager.GetString("Error_InputsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码错误.
        /// </summary>
        public static string Error_InvalidPassword {
            get {
                return ResourceManager.GetString("Error_InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码错误，连续输入三次错误将锁定账号！.
        /// </summary>
        public static string Error_InvalidPasswordWithLockWarning {
            get {
                return ResourceManager.GetString("Error_InvalidPasswordWithLockWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 验证码错误.
        /// </summary>
        public static string Error_InvalidVerificationCode {
            get {
                return ResourceManager.GetString("Error_InvalidVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请确认日志库 ID:{0} 的 Enabled 为 true.
        /// </summary>
        public static string Error_LogDatabase_EnsureEnabled_Arg0 {
            get {
                return ResourceManager.GetString("Error_LogDatabase_EnsureEnabled_Arg0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前页码超出表格最大页码.
        /// </summary>
        public static string Error_PageNumberExceedsLimit {
            get {
                return ResourceManager.GetString("Error_PageNumberExceedsLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 页码必须是 &gt;=1 的整数.
        /// </summary>
        public static string Error_PageNumberInvalid {
            get {
                return ResourceManager.GetString("Error_PageNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 每页条数必须是 &gt;=1 并且 &lt;= 100 的整数.
        /// </summary>
        public static string Error_PageSizeInvalid {
            get {
                return ResourceManager.GetString("Error_PageSizeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新密码不能与旧密码相同.
        /// </summary>
        public static string Error_PasswordSameAsOld {
            get {
                return ResourceManager.GetString("Error_PasswordSameAsOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暂停失败，请重试！.
        /// </summary>
        public static string Error_PauseFailed {
            get {
                return ResourceManager.GetString("Error_PauseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您无权修改或删除比你角色等级更高的数据！.
        /// </summary>
        public static string Error_PermissionDenied_HigherRoleData {
            get {
                return ResourceManager.GetString("Error_PermissionDenied_HigherRoleData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 恢复失败，请重试！.
        /// </summary>
        public static string Error_RestoreFailed {
            get {
                return ResourceManager.GetString("Error_RestoreFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to simple模式下请设置作业间隔执行秒数！.
        /// </summary>
        public static string Error_SetIntervalSeconds {
            get {
                return ResourceManager.GetString("Error_SetIntervalSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token已过期，请重新登录！.
        /// </summary>
        public static string Error_TokenExpired {
            get {
                return ResourceManager.GetString("Error_TokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token解析失败，请重新登录！.
        /// </summary>
        public static string Error_TokenParseFailed {
            get {
                return ResourceManager.GetString("Error_TokenParseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token已被禁止使用，请重新登录！.
        /// </summary>
        public static string Error_TokenRevoked {
            get {
                return ResourceManager.GetString("Error_TokenRevoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新列和排除列不能同时使用.
        /// </summary>
        public static string Error_UpdateAndExcludeConflict {
            get {
                return ResourceManager.GetString("Error_UpdateAndExcludeConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户未激活.
        /// </summary>
        public static string Error_UserNotActivated {
            get {
                return ResourceManager.GetString("Error_UserNotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户不存在.
        /// </summary>
        public static string Error_UserNotFound {
            get {
                return ResourceManager.GetString("Error_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 验证码已过期.
        /// </summary>
        public static string Error_VerificationCodeExpired {
            get {
                return ResourceManager.GetString("Error_VerificationCodeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 内容类型.
        /// </summary>
        public static string File_ContentType {
            get {
                return ResourceManager.GetString("File_ContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 内容类型名称.
        /// </summary>
        public static string File_ContentTypeName {
            get {
                return ResourceManager.GetString("File_ContentTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 内容类型(en).
        /// </summary>
        public static string File_ContentTypeNameEn {
            get {
                return ResourceManager.GetString("File_ContentTypeNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 存储路径.
        /// </summary>
        public static string File_FilePath {
            get {
                return ResourceManager.GetString("File_FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新名称.
        /// </summary>
        public static string File_NewName {
            get {
                return ResourceManager.GetString("File_NewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 源名称.
        /// </summary>
        public static string File_OriginalName {
            get {
                return ResourceManager.GetString("File_OriginalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件大小.
        /// </summary>
        public static string File_Size {
            get {
                return ResourceManager.GetString("File_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否启用.
        /// </summary>
        public static string Job_Enabled {
            get {
                return ResourceManager.GetString("Job_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 岗位名称.
        /// </summary>
        public static string Job_Name {
            get {
                return ResourceManager.GetString("Job_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 组件.
        /// </summary>
        public static string Menu_Component {
            get {
                return ResourceManager.GetString("Menu_Component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 组件名称.
        /// </summary>
        public static string Menu_ComponentName {
            get {
                return ResourceManager.GetString("Menu_ComponentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否启用.
        /// </summary>
        public static string Menu_Enabled {
            get {
                return ResourceManager.GetString("Menu_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否隐藏.
        /// </summary>
        public static string Menu_Hidden {
            get {
                return ResourceManager.GetString("Menu_Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon图标.
        /// </summary>
        public static string Menu_Icon {
            get {
                return ResourceManager.GetString("Menu_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否IFrame.
        /// </summary>
        public static string Menu_IFrame {
            get {
                return ResourceManager.GetString("Menu_IFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否缓存.
        /// </summary>
        public static string Menu_KeepAlive {
            get {
                return ResourceManager.GetString("Menu_KeepAlive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 组件路径.
        /// </summary>
        public static string Menu_Path {
            get {
                return ResourceManager.GetString("Menu_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 权限标识符.
        /// </summary>
        public static string Menu_Permission {
            get {
                return ResourceManager.GetString("Menu_Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 菜单父ID.
        /// </summary>
        public static string Menu_PId {
            get {
                return ResourceManager.GetString("Menu_PId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 子菜单个数.
        /// </summary>
        public static string Menu_SubCount {
            get {
                return ResourceManager.GetString("Menu_SubCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 菜单标题.
        /// </summary>
        public static string Menu_Title {
            get {
                return ResourceManager.GetString("Menu_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 菜单类型.
        /// </summary>
        public static string Menu_Type {
            get {
                return ResourceManager.GetString("Menu_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录账号.
        /// </summary>
        public static string Online_Account {
            get {
                return ResourceManager.GetString("Online_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浏览器名称.
        /// </summary>
        public static string Online_BrowserName {
            get {
                return ResourceManager.GetString("Online_BrowserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户部门.
        /// </summary>
        public static string Online_Dept {
            get {
                return ResourceManager.GetString("Online_Dept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设备类型.
        /// </summary>
        public static string Online_DeviceType {
            get {
                return ResourceManager.GetString("Online_DeviceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP地址.
        /// </summary>
        public static string Online_IpAddress {
            get {
                return ResourceManager.GetString("Online_IpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录IP.
        /// </summary>
        public static string Online_LoginIp {
            get {
                return ResourceManager.GetString("Online_LoginIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录时间.
        /// </summary>
        public static string Online_LoginTime {
            get {
                return ResourceManager.GetString("Online_LoginTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户昵称.
        /// </summary>
        public static string Online_NickName {
            get {
                return ResourceManager.GetString("Online_NickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 令牌.
        /// </summary>
        public static string Online_Onlinekey {
            get {
                return ResourceManager.GetString("Online_Onlinekey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作系统.
        /// </summary>
        public static string Online_OperatingSystem {
            get {
                return ResourceManager.GetString("Online_OperatingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 版本号.
        /// </summary>
        public static string Online_Version {
            get {
                return ResourceManager.GetString("Online_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否启用.
        /// </summary>
        public static string Parameter_Enabled {
            get {
                return ResourceManager.GetString("Parameter_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 参数名称.
        /// </summary>
        public static string Parameter_Name {
            get {
                return ResourceManager.GetString("Parameter_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 参数值.
        /// </summary>
        public static string Parameter_Value {
            get {
                return ResourceManager.GetString("Parameter_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密件抄送.
        /// </summary>
        public static string QueuedEmail_Bcc {
            get {
                return ResourceManager.GetString("QueuedEmail_Bcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 内容.
        /// </summary>
        public static string QueuedEmail_Body {
            get {
                return ResourceManager.GetString("QueuedEmail_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抄送.
        /// </summary>
        public static string QueuedEmail_CC {
            get {
                return ResourceManager.GetString("QueuedEmail_CC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发件邮箱ID.
        /// </summary>
        public static string QueuedEmail_EmailAccountId {
            get {
                return ResourceManager.GetString("QueuedEmail_EmailAccountId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发件邮箱.
        /// </summary>
        public static string QueuedEmail_From {
            get {
                return ResourceManager.GetString("QueuedEmail_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发件人名称.
        /// </summary>
        public static string QueuedEmail_FromName {
            get {
                return ResourceManager.GetString("QueuedEmail_FromName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 优先级.
        /// </summary>
        public static string QueuedEmail_Priority {
            get {
                return ResourceManager.GetString("QueuedEmail_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回复邮箱.
        /// </summary>
        public static string QueuedEmail_ReplyTo {
            get {
                return ResourceManager.GetString("QueuedEmail_ReplyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回复人名称.
        /// </summary>
        public static string QueuedEmail_ReplyToName {
            get {
                return ResourceManager.GetString("QueuedEmail_ReplyToName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发送时间.
        /// </summary>
        public static string QueuedEmail_SendTime {
            get {
                return ResourceManager.GetString("QueuedEmail_SendTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发送上限次数.
        /// </summary>
        public static string QueuedEmail_SentTries {
            get {
                return ResourceManager.GetString("QueuedEmail_SentTries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 标题.
        /// </summary>
        public static string QueuedEmail_Subject {
            get {
                return ResourceManager.GetString("QueuedEmail_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 收件邮箱.
        /// </summary>
        public static string QueuedEmail_To {
            get {
                return ResourceManager.GetString("QueuedEmail_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 收件人名称.
        /// </summary>
        public static string QueuedEmail_ToName {
            get {
                return ResourceManager.GetString("QueuedEmail_ToName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据部门.
        /// </summary>
        public static string Role_DataDept {
            get {
                return ResourceManager.GetString("Role_DataDept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据权限类型.
        /// </summary>
        public static string Role_DataScopeType {
            get {
                return ResourceManager.GetString("Role_DataScopeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 角色等级.
        /// </summary>
        public static string Role_Level {
            get {
                return ResourceManager.GetString("Role_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 角色名称.
        /// </summary>
        public static string Role_Name {
            get {
                return ResourceManager.GetString("Role_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 权限标识.
        /// </summary>
        public static string Role_Permission {
            get {
                return ResourceManager.GetString("Role_Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api路由.
        /// </summary>
        public static string Sys_Api {
            get {
                return ResourceManager.GetString("Sys_Api", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App应用密钥.
        /// </summary>
        public static string Sys_AppSecret {
            get {
                return ResourceManager.GetString("Sys_AppSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 审计日志.
        /// </summary>
        public static string Sys_AuditLog {
            get {
                return ResourceManager.GetString("Sys_AuditLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 验证码.
        /// </summary>
        public static string Sys_Captcha {
            get {
                return ResourceManager.GetString("Sys_Captcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 验证码Id.
        /// </summary>
        public static string Sys_CaptchaId {
            get {
                return ResourceManager.GetString("Sys_CaptchaId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 执行创建.
        /// </summary>
        public static string Sys_Create {
            get {
                return ResourceManager.GetString("Sys_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建人.
        /// </summary>
        public static string Sys_CreateBy {
            get {
                return ResourceManager.GetString("Sys_CreateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建时间.
        /// </summary>
        public static string Sys_CreateTime {
            get {
                return ResourceManager.GetString("Sys_CreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 执行删除.
        /// </summary>
        public static string Sys_Delete {
            get {
                return ResourceManager.GetString("Sys_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除时间.
        /// </summary>
        public static string Sys_DeletedTime {
            get {
                return ResourceManager.GetString("Sys_DeletedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部门.
        /// </summary>
        public static string Sys_Dept {
            get {
                return ResourceManager.GetString("Sys_Dept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 描述.
        /// </summary>
        public static string Sys_Description {
            get {
                return ResourceManager.GetString("Sys_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字典.
        /// </summary>
        public static string Sys_Dict {
            get {
                return ResourceManager.GetString("Sys_Dict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字典明细.
        /// </summary>
        public static string Sys_DictDetail {
            get {
                return ResourceManager.GetString("Sys_DictDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 禁用.
        /// </summary>
        public static string Sys_Disabled {
            get {
                return ResourceManager.GetString("Sys_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 执行编辑.
        /// </summary>
        public static string Sys_Edit {
            get {
                return ResourceManager.GetString("Sys_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 邮箱.
        /// </summary>
        public static string Sys_Email {
            get {
                return ResourceManager.GetString("Sys_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 邮件账户.
        /// </summary>
        public static string Sys_EmailAccount {
            get {
                return ResourceManager.GetString("Sys_EmailAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 邮件模板.
        /// </summary>
        public static string Sys_EmailMessageTemplate {
            get {
                return ResourceManager.GetString("Sys_EmailMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用.
        /// </summary>
        public static string Sys_Enabled {
            get {
                return ResourceManager.GetString("Sys_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 异常日志.
        /// </summary>
        public static string Sys_ExceptionLog {
            get {
                return ResourceManager.GetString("Sys_ExceptionLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 执行导出.
        /// </summary>
        public static string Sys_Export {
            get {
                return ResourceManager.GetString("Sys_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件记录.
        /// </summary>
        public static string Sys_FileRecord {
            get {
                return ResourceManager.GetString("Sys_FileRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请求失败.
        /// </summary>
        public static string Sys_HttpBadRequest {
            get {
                return ResourceManager.GetString("Sys_HttpBadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建成功.
        /// </summary>
        public static string Sys_HttpCreated {
            get {
                return ResourceManager.GetString("Sys_HttpCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除成功.
        /// </summary>
        public static string Sys_HttpDelete {
            get {
                return ResourceManager.GetString("Sys_HttpDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抱歉，您访问权限等级不够.
        /// </summary>
        public static string Sys_HttpForbidden {
            get {
                return ResourceManager.GetString("Sys_HttpForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统异常.
        /// </summary>
        public static string Sys_HttpInternalServerError {
            get {
                return ResourceManager.GetString("Sys_HttpInternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑成功.
        /// </summary>
        public static string Sys_HttpNoContent {
            get {
                return ResourceManager.GetString("Sys_HttpNoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请求成功.
        /// </summary>
        public static string Sys_HttpOK {
            get {
                return ResourceManager.GetString("Sys_HttpOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抱歉，您无权访问该接口.
        /// </summary>
        public static string Sys_HttpUnauthorized {
            get {
                return ResourceManager.GetString("Sys_HttpUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Sys_Id {
            get {
                return ResourceManager.GetString("Sys_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否删除.
        /// </summary>
        public static string Sys_IsDeleted {
            get {
                return ResourceManager.GetString("Sys_IsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 岗位.
        /// </summary>
        public static string Sys_Job {
            get {
                return ResourceManager.GetString("Sys_Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 列表.
        /// </summary>
        public static string Sys_List {
            get {
                return ResourceManager.GetString("Sys_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 菜单.
        /// </summary>
        public static string Sys_Menu {
            get {
                return ResourceManager.GetString("Sys_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名称.
        /// </summary>
        public static string Sys_Name {
            get {
                return ResourceManager.GetString("Sys_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在线用户.
        /// </summary>
        public static string Sys_OnlineUser {
            get {
                return ResourceManager.GetString("Sys_OnlineUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统参数.
        /// </summary>
        public static string Sys_Parameter {
            get {
                return ResourceManager.GetString("Sys_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 电话.
        /// </summary>
        public static string Sys_Phone {
            get {
                return ResourceManager.GetString("Sys_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作业调度.
        /// </summary>
        public static string Sys_QuartzNet {
            get {
                return ResourceManager.GetString("Sys_QuartzNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作业调度日志.
        /// </summary>
        public static string Sys_QuartzNetLog {
            get {
                return ResourceManager.GetString("Sys_QuartzNetLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 执行查询.
        /// </summary>
        public static string Sys_Query {
            get {
                return ResourceManager.GetString("Sys_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 队列邮件.
        /// </summary>
        public static string Sys_QueuedEmail {
            get {
                return ResourceManager.GetString("Sys_QueuedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 角色.
        /// </summary>
        public static string Sys_Role {
            get {
                return ResourceManager.GetString("Sys_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 服务器监控.
        /// </summary>
        public static string Sys_ServiceMonitoring {
            get {
                return ResourceManager.GetString("Sys_ServiceMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排序.
        /// </summary>
        public static string Sys_Sort {
            get {
                return ResourceManager.GetString("Sys_Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作业日志.
        /// </summary>
        public static string Sys_TaskLog {
            get {
                return ResourceManager.GetString("Sys_TaskLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 租户.
        /// </summary>
        public static string Sys_Tenant {
            get {
                return ResourceManager.GetString("Sys_Tenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新人.
        /// </summary>
        public static string Sys_UpdateBy {
            get {
                return ResourceManager.GetString("Sys_UpdateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新时间.
        /// </summary>
        public static string Sys_UpdateTime {
            get {
                return ResourceManager.GetString("Sys_UpdateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户.
        /// </summary>
        public static string Sys_User {
            get {
                return ResourceManager.GetString("Sys_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 告警邮箱.
        /// </summary>
        public static string Task_AlertEmail {
            get {
                return ResourceManager.GetString("Task_AlertEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 命名空间.
        /// </summary>
        public static string Task_AssemblyName {
            get {
                return ResourceManager.GetString("Task_AssemblyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 执行类.
        /// </summary>
        public static string Task_ClassName {
            get {
                return ResourceManager.GetString("Task_ClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cron表达式.
        /// </summary>
        public static string Task_Cron {
            get {
                return ResourceManager.GetString("Task_Cron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 循环执行次数.
        /// </summary>
        public static string Task_CycleRunTimes {
            get {
                return ResourceManager.GetString("Task_CycleRunTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结束时间.
        /// </summary>
        public static string Task_EndTime {
            get {
                return ResourceManager.GetString("Task_EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 执行间隔时间.
        /// </summary>
        public static string Task_IntervalSecond {
            get {
                return ResourceManager.GetString("Task_IntervalSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否启动.
        /// </summary>
        public static string Task_IsEnable {
            get {
                return ResourceManager.GetString("Task_IsEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否是否继续.
        /// </summary>
        public static string Task_PauseAfterFailure {
            get {
                return ResourceManager.GetString("Task_PauseAfterFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 负责人.
        /// </summary>
        public static string Task_Principal {
            get {
                return ResourceManager.GetString("Task_Principal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 执行传参.
        /// </summary>
        public static string Task_RunParams {
            get {
                return ResourceManager.GetString("Task_RunParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 执行次数.
        /// </summary>
        public static string Task_RunTimes {
            get {
                return ResourceManager.GetString("Task_RunTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始时间.
        /// </summary>
        public static string Task_StartTime {
            get {
                return ResourceManager.GetString("Task_StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任务组.
        /// </summary>
        public static string Task_TaskGroup {
            get {
                return ResourceManager.GetString("Task_TaskGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任务名称.
        /// </summary>
        public static string Task_TaskName {
            get {
                return ResourceManager.GetString("Task_TaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 触发器状态.
        /// </summary>
        public static string Task_TriggerStatus {
            get {
                return ResourceManager.GetString("Task_TriggerStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任务类型.
        /// </summary>
        public static string Task_TriggerType {
            get {
                return ResourceManager.GetString("Task_TriggerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 异常详情.
        /// </summary>
        public static string TaskLog_ExceptionDetail {
            get {
                return ResourceManager.GetString("TaskLog_ExceptionDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 执行耗时(s).
        /// </summary>
        public static string TaskLog_ExecutionDuration {
            get {
                return ResourceManager.GetString("TaskLog_ExecutionDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否成功.
        /// </summary>
        public static string TaskLog_IsSuccess {
            get {
                return ResourceManager.GetString("TaskLog_IsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任务ID.
        /// </summary>
        public static string TaskLog_TaskId {
            get {
                return ResourceManager.GetString("TaskLog_TaskId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据库标识ID.
        /// </summary>
        public static string Tenant_ConfigId {
            get {
                return ResourceManager.GetString("Tenant_ConfigId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据库链接字符串.
        /// </summary>
        public static string Tenant_Connection {
            get {
                return ResourceManager.GetString("Tenant_Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据库类型.
        /// </summary>
        public static string Tenant_DbType {
            get {
                return ResourceManager.GetString("Tenant_DbType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 租户ID.
        /// </summary>
        public static string Tenant_Id {
            get {
                return ResourceManager.GetString("Tenant_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 租户名称.
        /// </summary>
        public static string Tenant_Name {
            get {
                return ResourceManager.GetString("Tenant_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 租户类型.
        /// </summary>
        public static string Tenant_TenantType {
            get {
                return ResourceManager.GetString("Tenant_TenantType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 头像路径.
        /// </summary>
        public static string User_AvatarPath {
            get {
                return ResourceManager.GetString("User_AvatarPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认新密码.
        /// </summary>
        public static string User_ConfirmPassword {
            get {
                return ResourceManager.GetString("User_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部门ID.
        /// </summary>
        public static string User_DeptId {
            get {
                return ResourceManager.GetString("User_DeptId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户邮箱.
        /// </summary>
        public static string User_Email {
            get {
                return ResourceManager.GetString("User_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否激活.
        /// </summary>
        public static string User_Enabled {
            get {
                return ResourceManager.GetString("User_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 性别.
        /// </summary>
        public static string User_Gender {
            get {
                return ResourceManager.GetString("User_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新密码.
        /// </summary>
        public static string User_NewPassword {
            get {
                return ResourceManager.GetString("User_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户昵称.
        /// </summary>
        public static string User_NickName {
            get {
                return ResourceManager.GetString("User_NickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 旧密码.
        /// </summary>
        public static string User_OldPassword {
            get {
                return ResourceManager.GetString("User_OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户密码.
        /// </summary>
        public static string User_Password {
            get {
                return ResourceManager.GetString("User_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最后修改密码时间.
        /// </summary>
        public static string User_PasswordReSetTime {
            get {
                return ResourceManager.GetString("User_PasswordReSetTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户名称.
        /// </summary>
        public static string User_Username {
            get {
                return ResourceManager.GetString("User_Username", resourceCulture);
            }
        }
    }
}
